# -*- coding: utf-8 -*-
"""2 parcial

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W-Rg8_xDX_iZDruilxL8ueNU4I5lbtLs

# **UCEVA Costo del semestre por programa y periodo academico.**
"""

#Librerias a utilizar
import pandas as pd #import pandas
import glob 
import numpy as np
#Librerias para graficas
import seaborn as sns
import matplotlib as plt

url='https://raw.githubusercontent.com/geral3434/archivocsv/main/UCEVA_Costo_del_semestre_por_programa_y_periodo_academico.csv'

df= pd.read_csv(url)

pd.read_csv(url)

df.head(10)

df.columns

df.shape

df.info

df.info()

df.dtypes

pd.unique(df['Programa Académico'])

df.filter(regex='^Programa Académico*', axis=1).sample(10)

df.groupby('Programa Académico').mean()

df.sort_values(by='Valor del Concepto.',ascending=True)[['Programa Académico', 'Semestre','Jornada']].head(5)

df.sort_values(by='Valor del Concepto.',ascending=False)[['Programa Académico', 'Semestre','Jornada']].head(5)

df.describe()

sns.countplot(x="Programa Académico", data = df)
df. loc[:, "Programa Académico"] . value_counts ( )

df.plot()

sns.countplot(x="Jornada", data = df)
df. loc[:, "Jornada"] . value_counts ( )